apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-knative
  namespace: demo
spec:
  template:
    metadata:
      name: flask-knative-v1
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/compact-arena-501908-v9/flask-demo-repo/flask-redis-demo:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-config
          env:
            - name: APP_VERSION
              value: "v1"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000